#!/bin/bash

set -e
set -x

CONTAINER=ttclabs/ubuntu_pam_fido2

time docker pull "$CONTAINER"

time docker run -e TARGET_BRANCH="${TARGET_BRANCH}" \
	--cap-add SYS_PTRACE \
	--volume ${TRAVIS_BUILD_DIR}:/app/ \
	--workdir /app \
	"${CONTAINER}" \
	bash -c "/meson/meson-0.54.0rc1/meson.py ubuntu_build && ninja -C ubuntu_build pam-fido2_ubuntu.deb"
